package com.lasallecollegevancouver.countriesrecyclerviewapp

class AppData
{
    companion object
    {
        val countries = arrayOf(
            "Canada",
            "United States",
            "Brazil",
            "Argentina",
            "United Kingdom",
            "France",
            "Germany",
            "Italy",
            "Spain",
            "Portugal",
            "Netherlands",
            "Sweden",
            "Norway",
            "Japan",
            "South Korea",
            "China",
            "India",
            "Australia",
            "New Zealand",
            "Egypt",
            "South Africa",
            "Nigeria",
            "Kenya",
            "Morocco",
            "Turkey",
            "Greece",
            "Ireland",
            "Poland",
            "Ukraine",
            "Mexico",
            "Guatemala",
            "Belize",
            "Honduras",
            "El Salvador",
            "Nicaragua",
            "Costa Rica",
            "Panama",
            "Cuba",
            "Dominican Republic",
            "Puerto Rico",
            "Haiti",
            "Colombia",
            "Ecuador",
            "Peru",
            "Bolivia",
            "Chile",
            "Uruguay",
            "Paraguay",
            "Guyana",
            "Suriname",
            "French Guiana",
            "Jamaica",
            "Trinidad and Tobago",
            "Barbados",
            "Bahamas",
            "Grenada",
            "Venezuela"
        )
    }
}